bin/pmm-update
=> Revert "PMM-3530 Update from 1.17. to 1.17.1 is failed"

bin/pmm-update-check, bin/pmm-update-stage2
* on pmm v1 all available v2 scenarios are skipped
* on pmm v2 all available v1 scenarios are skipped
=> PMM-3669 get correct available version for update

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/523
=> PMM-4940 Limit the list of packages during the update

ansible/playbook/tasks/update.yml
server docker - perconalab/pmm-server-fb:PR-543-e736471
https://pmm.cd.percona.com/job/pmm-submodules/view/change-requests/job/PR-543/
=> PMM-5029 upload snapshots to percona not working

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/597
=> PMM-5215 Remove 'mariadb-libs' rpm to avoid 'obsolete' issue

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/619
=> PMM-5271 Fix automatic resizing of LVM volumes.

ansible/v011703/main.yml
https://github.com/Percona-Lab/pmm-submodules/pull/632
=> PMM-5273 Fix automatic resizing of LVM volumes.

.devcontainer/devcontainer.json, .devcontainer/install-dev-tools.sh, .travis.yml, ansible/playbook/tasks/update.yml, pkg/yum/yum_test.go
=> PMM-5655 Remove leftovers of Grafana plugins

ansible/playbook/tasks/update.yml
Added alertmanager to ansible playbook
=> PMM-5558 added alertmanager

.devcontainer/install-dev-tools.sh, ansible/playbook/tasks/update.yml
It should be created before pmm-managed restart to let it
create /srv/alertmanager/alertmanager.base.yml
=> PMM-5890 Create Alertmanager directory earlier.

ansible/playbook/tasks/update.yml
Install dbaas-controller using pmm-update.
=> PMM-6119 dbaas controller packaging

ansible/playbook/tasks/update.yml
=> PMM-6334 Start using new snapshots server

ansible/playbook/tasks/update.yml
=> PMM-6503 install latest versions of grafana plugins

ansible/playbook/tasks/update.yml
=> PMM-6119 Update dbaas-controller

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1020
=> PMM-6389 Add VictoriaMetrics

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1137
=> PMM-6639 Incomplete container detection in update

ansible/playbook/tasks/update.yml
FB https://github.com/Percona-Lab/pmm-submodules/pull/1429
=> PMM-6766 remove qan app

Gopkg.lock, Gopkg.toml
=> Changes from 2.16

ansible/playbook/tasks/update.yml
1. Set `is_dbaas_on` variable instead of using jinja template in when which is not recommended.
1. Use `loop` instead of `with_nested` which should provide desired behavior.
=> PMM-7766 restart dbaas controller on update

ansible/playbook/tasks/update.yml
https://jira.percona.com/browse/PMM-8193
Should come together with https://github.com/Percona-Lab/percona-images/pull/102
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1823
=> PMM-8193: Update minfds during update

ansible/playbook/tasks/update.yml
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1852
=> PMM-8060 Stop pmm-agent systemd service on update.

ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1856
=> PMM-8266 remove prometheus from image

README.md, ansible/playbook/tasks/update.yml
https://github.com/Percona-Lab/pmm-submodules/pull/1859
=> PMM-7627 manage nginx logs using supervisor

ansible/playbook/tasks/update.yml
=> Changes from 2.19.0

.travis.yml, ansible/playbook/tasks/update.yml
* PMM-8492 remove experimental repo from old versions
=> PMM-8492 remove experimental repo from old versions (#141)

ansible/playbook/tasks/update.yml
Restarts will be handled by PMM managed. https://github.com/percona/pmm-managed/pull/821
=> Remove dbaas-controller restart as it's handled by pmm-managed

.github/CODEOWNERS, ansible/playbook/tasks/files/datasources.yml, ansible/playbook/tasks/update.yml
See also https://github.com/percona/pmm-server/pull/315
=> PMM-9061 migrate to other provision mechanism

ansible/playbook/tasks/roles/initialization/tasks/main.yml, ansible/playbook/tasks/update.yml
We didn't upgrade the Grafana database schema to the latest version and we have a different database structure in different PMM versions.
=> PMM-9260 fix grafana folders bug

ansible/playbook/tasks/roles/grafana/tasks/main.yml
=> PMM-7 fix permission issue with grafana config

ansible/playbook/tasks/roles/nginx/files/conf.d/pmm.conf
PMM-10285
Build: SUBMODULES-2631
=> PMM-10285 Fix swagger CVE.

ansible/playbook/tasks/files/datasources.yml
PMM-10312
Build: SUBMODULES-2638
=> PMM-10312 add clickhouse datasource variable

ansible/playbook/tasks/update.yml
PMM-10036
Build: SUBMODULES-2665
=> PMM-10036 Remove pmm-server package

ansible/playbook/tasks/roles/dashboards_upgrade/tasks/main.yml, ansible/playbook/tasks/roles/postgres/tasks/main.yml
=>  PMM-10343 fix upgrade to dev-latest

README.md, ansible/playbook/tasks/roles/initialization/tasks/main.yml, ansible/playbook/tasks/update.yml
This reverts commit d88532d2d951c69d9997ac273e95aa1bace85d25.
PMM-10643
Build: SUBMODULES-0
=> Revert "PMM-9503 remove prometheus (#237)"

ansible/playbook/tasks/roles/nginx/files/ssl/upgrade-certificate
=> Update upgrade-certificate script

.github/pull_request_template.md, ansible/playbook/tasks/roles/initialization/tasks/main.yml, ansible/playbook/tasks/update.yml
PMM-10735
Build: SUBMODULES-2791
- https://github.com/percona/pmm/pull/1247
=> PMM-10735 fix sudden service stoppage

.github/pull_request_template.md, ansible/playbook/tasks/roles/initialization/tasks/main.yml, ansible/playbook/tasks/update.yml
PMM-0
Build: SUBMODULES-0
- Links to other linked pull requests (optional).
=> PMM-10735 fix supervisord service launch

ansible/playbook/tasks/roles/initialization/tasks/main.yml
PMM-10858
Build: SUBMODULES-2862
=> PMM-10858 latest version fix
